// <auto-generated />
namespace Frelsex.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UpUtenteCliente_ID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpUtenteCliente_ID));
        
        string IMigrationMetadata.Id
        {
            get { return "202403070112381_UpUtente-Cliente_ID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
